name: Build

on:
    pull_request:
        branches-ignore:
            - 'ga-ignore-**'

jobs:
    build-Windows:
        name: Build Windows
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                build-type: [Debug, Release]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: lukka/get-cmake@latest
              with:
                cmakeVersion: '3.21.0'

            - uses: microsoft/setup-msbuild@v1.1
              with:
                vs-version: '17.0'
                msbuild-architecture: 'x64'

            - uses: lukka/run-vcpkg@v11
              with:
                vcpkgGitCommitId: a42af01b72c28a8e1d7b48107b33e4f286a55ef6

            - name: Create build directory
              run: mkdir -p build

            - name: Configure
              run: cmake -S . -B build --preset=default -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
                
            - name: Build
              run: cmake --build build --config ${{ matrix.build-type }} --target ALL_BUILD -- /m:$(nproc) /t:TreatWarningsAsErrors=false

    build-linux:
        name: Build Linux
        runs-on: [Linux, self-hosted]
        strategy:
          fail-fast: false
          matrix:
              build-type: [Debug, Release]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Create build directory
              run: mkdir -p build

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                vcpkgGitCommitId: a42af01b72c28a8e1d7b48107b33e4f286a55ef6
    
            - name: Configure
              run: cmake -S . -B build --preset=default -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
                    
            - name: Build
              run: cmake --build build --config ${{ matrix.build-type }} --target all -- -j$(nproc)