name: Build

on:
    pull_request:
        branches-ignore:
            - 'ga-ignore-**'
    push:
        branches-ignore:
            - 'ga-ignore-**'

jobs:
    build-Windows:
        name: Build Windows
        runs-on: [Windows, self-hosted]
        strategy:
            fail-fast: false
            matrix:
                build-type: [Debug, Release]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Create build directory
              run: mkdir -p build

            - name: Configure
              run: cmake -S . -B build --preset=default -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
                
            - name: Build
              run: cmake --build build --config ${{ matrix.build-type }} --target all -- -j$(nproc)

    build-linux:
        name: Build Linux
        runs-on: [Linux, self-hosted]
        strategy:
          fail-fast: false
          matrix:
              build-type: [Debug, Release]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Create build directory
              run: mkdir -p build
    
            - name: Configure
              run: cmake -S . -B build --preset=default -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
                    
            - name: Build
              run: cmake --build build --config ${{ matrix.build-type }} --target all -- -j$(nproc)

    #         - name: install winget
    #           uses: Cyberboss/install-winget@v1
    #           with:
    #             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #         - name: Create cache directory
    #           run: mkdir -p ~/scoop/cache

    #         - name: Cache dependencies
    #           uses: actions/cache@v3
    #           with:
    #             path: ~/scoop/cache
    #             key: ${{ runner.os }}-scoop-${{ hashFiles('**/scoop-install-script.ps1') }}

    #         - name: Install dependencies
    #           run: |
    #                 chmod +x ./scripts/install_dev_tools_windows.ps1
    #                 ./scripts/install_dev_tools_windows.ps1
    #         - name: Build
    #           run: |
    #                 chmod +x ./build_actions_windows.bat
    #                 ./build_actions_windows.bat