name: Build

on:
    pull_request:
        branches-ignore:
            - 'ga-ignore-**'

jobs:
    build-Windows:
        name: Build Windows
        runs-on: [Windows, self-hosted]
        strategy:
            fail-fast: false
            matrix:
                build-type: [Debug, Release]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11

            - name: Create build directory
              run: mkdir -p build

            - name: Configure
              run: cmake -S . -B build --preset=default -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
                
            - name: Build
              run: cmake --build build --config ${{ matrix.build-type }} --target all -- -j$(nproc)

    build-linux:
        name: Build Linux
        runs-on: [Linux, self-hosted]
        strategy:
          fail-fast: false
          matrix:
              build-type: [Debug, Release]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Create build directory
              run: mkdir -p build

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11
    
            - name: Configure
              run: cmake -S . -B build --preset=default -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
                    
            - name: Build
              run: cmake --build build --config ${{ matrix.build-type }} --target all -- -j$(nproc)