name: Code Quality

on:
    push:
        branches-ignore: 
            - 'ga-ignore-**'

jobs:
    lint:
        name: Lint
        runs-on: [Linux, self-hosted]
  
        steps:
          - uses: actions/checkout@v4
          - uses: wagoid/commitlint-github-action@v5

    commit-check:
        name: Commit Check
        runs-on: [Linux, self-hosted]
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: 3.x
        - uses: pre-commit/action@v3.0.0
        - uses: pre-commit-ci/lite-action@v1.0.1
          if: always()